package com.thedailywtf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Oct 28 11:27:15 BST 2010
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://thedailywtf.com/", name = "SubmitWTFSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SubmitWTFSoap {

    @WebResult(name = "SubmitResult", targetNamespace = "http://thedailywtf.com/")
    @RequestWrapper(localName = "Submit", targetNamespace = "http://thedailywtf.com/", className = "com.thedailywtf.Submit")
    @ResponseWrapper(localName = "SubmitResponse", targetNamespace = "http://thedailywtf.com/", className = "com.thedailywtf.SubmitResponse")
    @WebMethod(operationName = "Submit", action = "http://thedailywtf.com/Submit")
    public java.lang.String submit(
        @WebParam(name = "name", targetNamespace = "http://thedailywtf.com/")
        java.lang.String name,
        @WebParam(name = "emailAddress", targetNamespace = "http://thedailywtf.com/")
        java.lang.String emailAddress,
        @WebParam(name = "subject", targetNamespace = "http://thedailywtf.com/")
        java.lang.String subject,
        @WebParam(name = "comments", targetNamespace = "http://thedailywtf.com/")
        java.lang.String comments,
        @WebParam(name = "codeSubmission", targetNamespace = "http://thedailywtf.com/")
        java.lang.String codeSubmission,
        @WebParam(name = "doNotPublish", targetNamespace = "http://thedailywtf.com/")
        boolean doNotPublish
    );
}
