
/*
 * 
 */

package com.thedailywtf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Oct 28 11:27:15 BST 2010
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "SubmitWTF", 
                  wsdlLocation = "http://thedailywtf.com/SubmitWTF.asmx?wsdl",
                  targetNamespace = "http://thedailywtf.com/") 
public class SubmitWTF extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://thedailywtf.com/", "SubmitWTF");
    public final static QName SubmitWTFSoap12 = new QName("http://thedailywtf.com/", "SubmitWTFSoap12");
    public final static QName SubmitWTFSoap = new QName("http://thedailywtf.com/", "SubmitWTFSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://thedailywtf.com/SubmitWTF.asmx?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://thedailywtf.com/SubmitWTF.asmx?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SubmitWTF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubmitWTF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubmitWTF() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SubmitWTFSoap
     */
    @WebEndpoint(name = "SubmitWTFSoap12")
    public SubmitWTFSoap getSubmitWTFSoap12() {
        return super.getPort(SubmitWTFSoap12, SubmitWTFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubmitWTFSoap
     */
    @WebEndpoint(name = "SubmitWTFSoap12")
    public SubmitWTFSoap getSubmitWTFSoap12(WebServiceFeature... features) {
        return super.getPort(SubmitWTFSoap12, SubmitWTFSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns SubmitWTFSoap
     */
    @WebEndpoint(name = "SubmitWTFSoap")
    public SubmitWTFSoap getSubmitWTFSoap() {
        return super.getPort(SubmitWTFSoap, SubmitWTFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubmitWTFSoap
     */
    @WebEndpoint(name = "SubmitWTFSoap")
    public SubmitWTFSoap getSubmitWTFSoap(WebServiceFeature... features) {
        return super.getPort(SubmitWTFSoap, SubmitWTFSoap.class, features);
    }

}
